#!/bin/sh

usage() {
    echo Usage: `basename $0` '[-k keystorefile] [-p keystorepassword]' 
    exit 1
}

KEYSTOREFILE=
KEYSTOREPASSWD=

SOAPSETTINGSTPL=$TOOLCHAIN/samples/soap/settings.tpl
DEFAULTKEYSTORE=$TOOLCHAIN/samples/soap/keystore.jks
DEFAULTKSPASSWD=""
WSISETTINGSLOC=$TOOLCHAIN/soap/wsi-test-tools

set -- `getopt "k:p:" "$@"` || usage

while :
do
    case "$1" in
    -k) shift; KEYSTOREFILE="$1";;
    -p) shift; KEYSTOREPASSWD="$1";;
    --) break;
    esac 
    shift
done
shift 

if [ -z "$KEYSTOREFILE" ]; then
    KEYSTOREFILE=$DEFAULTKEYSTORE
fi 
if [ ! -e "$KEYSTOREFILE" ]; then
    KEYSTOREFILE=$DEFAULTKEYSTORE
fi
if [ -z "$KEYSTOREPASSWD" ]; then
    KEYSTOREPASSWD=$DEFAULTKSPASSWD
fi

echo "[keystore]: ($KEYSTOREFILE)"
echo "[passwd]: ($KEYSTOREPASSWD)"
echo "[wsisettingslocation]: ($WSISETTINGSLOC)"

echo "... Generating soapui-settings.xml in (`pwd`)"
sed -e "s|@@SSLSETTINGSKEYSTORE@@|$KEYSTOREFILE|" -e "s|@@SSLSETTINGSKEYSTOREPASSWD@@|$KEYSTOREPASSWD|" -e "s|@@WSISETTINGSLOCATION@@|$WSISETTINGSLOC|" $SOAPSETTINGSTPL > soapui-settings.xml

echo "... Done."

exit 0